name: Auto Update

on:
  schedule:
    - cron: '0 * * * *'  # 每小时的第0分钟执行
  workflow_dispatch: # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync with upstream
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: <upstream-repo-owner>/<upstream-repo-name>
          upstream_sync_branch: main
          test_mode: false

      - name: Modify clash.yml
        if: steps.sync.outputs.has_new_commits == 'true'
        run: |
          # 删除clash.yml的第一行和最后一行
          sed -i '1d;$d' clash.yml

      - name: Commit changes
        if: steps.sync.outputs.has_new_commits == 'true'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add clash.yml
          git commit -m 'Update clash.yml' || echo "No changes to commit"
          git push origin main
