name: Sync and Process
on:
  schedule:
    - cron: '0 * * * *'  # 每小时整点运行
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: 配置Git用户
        run: |
          git config --global user.name "AutoSyncBot"
          git config --global user.email "[email protected]"

      - name: 添加上游仓库
        run: git remote add upstream https://github.com/aiboboxx/clashfree.git

      - name: 拉取上游更新
        run: git fetch upstream

      - name: 合并上游分支 (允许强制合并)
        run: |
          git checkout main
          git merge --strategy-option=theirs upstream/main || true  # 强制接受上游更改
          git clean -f  # 清理未跟踪文件

      - name: 删除clash.yml首尾行
        run: |
          if [ -f clash.yml ]; then
            sed -i '1d;$d' clash.yml  # 直接修改原文件
            sed -i '/cipher: ss/d' clash.yml
          else
            echo "clash.yml不存在，跳过处理"
          fi

      - name: 提交并推送更改
        run: |
          git add clash.yml
          if ! git diff --quiet HEAD; then
            git commit -m "自动处理clash.yml并同步上游"
            git push origin main
          else
            echo "无变更需要提交"
          fi
